### PR TITLE
Translate Rose into Chinese

### PR DESCRIPTION
**Pull request by Ho-YuChen**
Thats my translation work
if u find something wrong or unsuit and need to re-edit，just let me know

### CODE REVIEW

**Comment by NAVECCIER** [comment]
The folder name for Chinese-Simplified should be zh_CN.lproj rather than ch.lproj

**Comment by Litteeen** [comment]
are there differences between simplified and traditional? If no I'll just make a duplicate with the other name

**Comment by Ho-YuChen** [comment]
Yes，there are some differences between simplified and traditional Chinese，but I'm a mainland Chinese，make traditional version may take longer time.let me find some time tomorrow and see if i can make it

**Comment by NAVECCIER** [comment]
Simplified Chinese is used in the China mainland now and almost all Chinese people can recognize them both.

**Comment by Ho-YuChen** [comment]
yes i realize that fault，should i upload another version with correct name or litteeen will change it on her own？

**Comment by Ho-YuChen** [comment]
like Naveccier said，almost all Chinese can realize and use simplified Chinese，do i still need to make another version？if you need it I'll get to work tomorrow

**Comment by Litteeen** [comment]
well, I personally don't need them, but feel free to change it to anything you need ^^

**Pull request merged**
